### ISSUE TITLE
TypeError: glob is not a function

### ISSUE THREAD

**Issue by StErMi** [ethereum-ts/TypeChain#408]
Hi I've installed and configured typechain for hardhat and when I try to compile/test my contract I get this error:

```
Compiling 4 files with 0.8.4
Generating typings for: 4 artifacts in dir: typechain for target: ethers-v5
An unexpected error occurred:

TypeError: glob is not a function
    at OverriddenTaskDefinition._action (/Users/MY_PROJECT/node_modules/@typechain/hardhat/src/index.ts:54:22)
    at Environment._runTaskDefinition (/Users/MY_PROJECT/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/MY_PROJECT/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/MY_PROJECT/node_modules/hardhat/src/builtin-tasks/compile.ts:1320:63)
    at Environment._runTaskDefinition (/Users/MY_PROJECT/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/MY_PROJECT/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/MY_PROJECT/node_modules/hardhat/src/builtin-tasks/compile.ts:1390:7)
    at Environment._runTaskDefinition (/Users/MY_PROJECT/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at OverriddenTaskDefinition._action (/Users/MY_PROJECT/node_modules/@typechain/hardhat/src/index.ts:23:5)
    at Environment._runTaskDefinition (/Users/MY_PROJECT/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
 ```

here's my package.json dependencies

```
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-solhint": "^2.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@openzeppelin/contracts": "^4.1.0",
    "@typechain/ethers-v5": "^2.0.0",
    "@typechain/hardhat": "^2.0.2",
    "@types/chai": "^4.2.19",
    "@types/mocha": "^8.2.2",
    "@types/node": "^15.12.4",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.3.1",
    "hardhat": "^2.4.0",
    "prettier": "^2.3.1",
    "prettier-plugin-solidity": "^1.0.0-beta.13",
    "solhint": "^2.3.1",
    "solhint-plugin-prettier": "^0.0.5",
    "solidity-coverage": "^0.7.16",
    "ts-node": "^10.0.0",
    "typechain": "^3.0.0",
    "typescript": "^4.3.4"
  ````

**Comment by fvictorio** [comment]
`@typechain/hardhat@2.0.2` has a peer dependency of `typechain ^5.0.0`, but you are installing `^3.0.0`, that's probably the issue.

**Comment by StErMi** [comment]
Don't ask me why but the whole problem was because when I did npm install it installed old packages not compatible one with another. Thanks to @fvictorio
