### ISSUE TITLE
truffle-5 example doesn't work out of the box

### ISSUE THREAD

**Issue by lebed2045** [ethereum-ts/TypeChain#510]
after you run `yarn` as REAME.md file says I end up with error:
```
/bin/sh: typechain: command not found
```
yarn add typechain also fails:
```
Error occured:  Couldn't find truffle-v5. Tried loading: @typechain/truffle-v5, typechain-target-truffle-v5, ~/ts_truffle-v5/truffle-v5.
Perhaps you forgot to install @typechain/truffle-v5?
Run with --show-stack-traces to see the full stacktrace
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

so, naturally do `yarn add @typechain/truffle-v5` and get success. 

But when I ran: `truffle test` the execution fails again:

```
Contract: MetaCoin
    1) should put 10000 MetaCoin in the first account
    > No events were emitted
    2) should call a function that depends on a linked library
    > No events were emitted
    3) should send coin correctly
    > No events were emitted


  0 passing (2s)
  3 failing

  1) Contract: MetaCoin
       should put 10000 MetaCoin in the first account:
     Error: MetaCoin has not been deployed to detected network (network/artifact mismatch)
      at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:249:1)
      at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:84:1)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (test/metacoin.ts:5:30)

  2) Contract: MetaCoin
       should call a function that depends on a linked library:
     Error: MetaCoin has not been deployed to detected network (network/artifact mismatch)
      at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:249:1)
      at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:84:1)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (test/metacoin.ts:11:30)

  3) Contract: MetaCoin
       should send coin correctly:
     Error: MetaCoin has not been deployed to detected network (network/artifact mismatch)
      at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:249:1)
      at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:84:1)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (test/metacoin.ts:22:30)
```

**expected behaviour:**
if I got into example and simply follow the README I expect that everything should work out of the box.

**Comment by hasparus** [comment]
@krzkaczor I'd expect the following error message in this case:

```
@typechain/truffle-v5-test
$ yarn generate-types && truffle test
$ node ../typechain/dist/cli/cli.js --target=../target-truffle-v5/dist/index.js './build/**/*.json'
 | Error occured:  Couldn't find ../target-truffle-v5/dist/index.js. Tried loading: @typechain/../target-truffle-v5/dist/index.js, typechain-target-../target-truffle-v5/dist/index.js, /mnt/d/workspace/TypeChain/packages/target-truffle-v5/dist/index.js.      
 | Perhaps you forgot to install @typechain/../target-truffle-v5/dist/index.js?
```

And seeing ` ~/ts_truffle-v5/truffle-v5` I think @lebed2045 might not be inside of the monorepo. We might need to add some more tooling if people expect to use examples as starters.
